import React, { Fragment } from "react";
import { Row, Col, Container } from "reactstrap";

class Fmedicalhistory extends React.Component {
  render() {
    return (
      <div className="paging">
        <Container className="bordercolor3">
          <Row className="bordercolor">
            <Col className="center1">
              <h3>MEDICAL HISTORY</h3>
            </Col>
          </Row>
          <Row>
            <Col>
              <Row className="bordercolor">
                <Col>
                  <h6>History of past Illness</h6>
                </Col>
              </Row>
              <div className="divprint2">{this.props.pastIllness}</div>
            </Col>
          </Row>
          <Row className="bordercolor">
            <Col>
              <h6> Family History of Illness</h6>
            </Col>
          </Row>
          {this.props.famIllness}
          <Row>
            <Col className="bordercolor">Height(cm): {this.props.height}</Col>
            <Col className="bordercolor">Weight(kg): {this.props.weight}</Col>
            <Col className="bordercolor">
              Blood Type: {this.props.bloodType}
            </Col>
          </Row>
          <Row className="bordercolor">
            <Col>
              <h6>Immunization</h6>
            </Col>
          </Row>
          {this.props.immunization}
          <Row className="bordercolor">
            <Col>
              <h6>Hospitalization</h6>
            </Col>
          </Row>
          {this.props.hospitalizations}
          <Row className="bordercolor">
            <Col>
              <h6>Operation</h6>
            </Col>
          </Row>
          {this.props.operations}
          <Row className="bordercolor">
            <Col>
              <h6>Medical History</h6>
            </Col>
          </Row>
          {this.props.medication}
          <Row className="bordercolor">
            <Col>
              <h6>Allergies</h6>
            </Col>
          </Row>
          {this.props.allergies}
          <Row className="bordercolor">
            <Col>
              <h6>Body Art</h6>
            </Col>
          </Row>
          {this.props.bodyArt}
          <Row className="bordercolor">
            <Col>
              <h6>Pertubing Habit</h6>
            </Col>
          </Row>
          {this.props.habits}
          <Row className="bordercolor">
            <Col>
              <h6>Visual Acuity</h6>
            </Col>
          </Row>
          {this.props.visualAcuity}

          {this.props.sex === "Female" ? (
            <Fragment>
              {" "}
              <Row className="bordercolor">
                <Col>
                  <h6>O.B Gyne History</h6>
                </Col>
              </Row>
              <Row>
                <Col className="bordercolor" xs="7">
                  Menach Year: {this.props.menarchYear}
                </Col>
                <Col className="bordercolor" xs="5">
                  Menach Age: {this.props.menarchAge}
                </Col>
                <Col className="bordercolor" xs="7">
                  Menstruation Duration: {this.props.mensDuration}
                </Col>
                <Col className="bordercolor" xs="5">
                  Dysmenorrhea: {this.props.dysmennorrhea}
                </Col>
              </Row>
            </Fragment>
          ) : null}
        </Container>
        <div class="divFooter">Medical Record ID: {this.props.id}</div>
        <div class="divFooter">Generated by: {this.props.name}</div>

        <div class="divFooter">Date & Time: {this.props.today}</div>
      </div>
    );
  }
}
export default Fmedicalhistory;
