import React from "react";
import { Row, Col, Container } from "reactstrap";

class Fpersonalrecord extends React.Component {
  render() {
    return (
      <div className="paging">
        <Container className="bordercolor3">
          <Row className="bordercolor">
            <Col className="center1">
              <h3>PERSONAL INFORMATION</h3>
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor">
              First Name: {this.props.firstName}
            </Col>
            <Col className="bordercolor">
              Middle Name: {this.props.middleName}
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor" xs="6">
              Last Name: {this.props.lastName}
            </Col>
            <Col className="bordercolor" xs="3">
              Sex: {this.props.sex}
            </Col>
            <Col className="bordercolor" xs="3">
              Age: {`${this.props.age} y/o`}
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor" xs="4">
              Birthdate: {this.props.birthdate}
            </Col>
            <Col className="bordercolor" xs="4">
              Civil Status: {this.props.civilStatus}
            </Col>
            <Col className="bordercolor" xs="4">
              Nationality: {this.props.nationality}
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor">Religion: {this.props.religion}</Col>
            <Col className="bordercolor">
              Contact No.: {this.props.contactNumber}
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor">
              <h6>IN CASE OF EMERGENCY</h6>
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor">
              Guardian Name: {this.props.guardianName}
            </Col>
            <Col className="bordercolor">
              Relationship: {this.props.relationship}
            </Col>
          </Row>
          <Row>
            <Col className="bordercolor">
              Contact No.: {this.props.guardianContactNo}
            </Col>
          </Row>
          <div class="divFooter">Medical Record ID: {this.props.id}</div>
          <div class="divFooter">
            Generated by: {this.props.firstName} {this.props.middleName}{" "}
            {this.props.lastName}
          </div>

          <div class="divFooter">Date & Time: {this.props.today}</div>
        </Container>
      </div>
    );
  }
}
export default Fpersonalrecord;
